[env:esp32dev]
platform = espressif32
board = esp32dev
; Si el puerto cambia, deja que PlatformIO lo detecte automáticamente.
; upload_port = /dev/ttyUSB0
framework = arduino
monitor_speed = 115200

lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.5
    bblanchon/ArduinoJson @ ^6.21.3
    miguelbalboa/MFRC522 @ ^1.4.10

